### ISSUE TITLE
Add Option to rename custom tag (and maybe properties) over the web ui

### ISSUE THREAD

**Issue by XENNOK** [toniebox-reverse-engineering/teddycloud#166] opened 2024-05-06 23:13 UTC
After placing the custom tag to the box and poping-up in the web interface it should be possible to give the tag a name in the ui instead of only editing the json itself.

**Comment by henryk86** [comment] 2024-10-11 06:57
duplicate of https://github.com/toniebox-reverse-engineering/teddycloud/issues/176 & https://github.com/toniebox-reverse-engineering/teddycloud/issues/156

**Closed by henryk86** 2024-10-11 06:57 UTC
Labels: duplicate
