### ISSUE TITLE
[FeatureRequest] teddycloud to support setting lower baud rate

### ISSUE THREAD

**Issue by HappyZ** [toniebox-reverse-engineering/teddycloud#258] opened 2024-11-17 05:19 UTC
Mine would only work at 115200 but you can only do 921600 with web browser method. esptool works but moving files from local to docker isn't the best user journey.

**Comment by henryk86** [comment] 2024-11-17 05:45
Duplicate of https://github.com/toniebox-reverse-engineering/teddycloud/issues/101

**Closed** 2024-11-17 05:45 UTC
Labels: duplicate, enhancement

**Comment by henryk86** [comment] 2024-11-17 09:29
Added this in current teddycloud_web PR to develop version (https://github.com/toniebox-reverse-engineering/teddycloud_web/pull/186). Please test it after merge in develop, as my box worked fine with the default value...

**Comment by Oggymator** [comment] 2024-12-02 21:58
when it will be released in the master branch?
have the problem that only 115200 work for me with ESP32 Box
